// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RubiksCube.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Rotations")]
    public partial class RotationsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Rotations.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Rotations", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cube Rotations")]
        [NUnit.Framework.TestCaseAttribute("Right", "1", "Green", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Up", "1", "Red", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Left", "1", "Blue", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Down", "1", "Orange", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Right", "2", "Yellow", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Up", "2", "Yellow", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Left", "2", "Yellow", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Down", "2", "Yellow", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Right", "3", "Blue", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Up", "3", "Orange", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Left", "3", "Green", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Down", "3", "Red", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Right", "4", "White", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Up", "4", "White", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Left", "4", "White", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Down", "4", "White", new string[0])]
        public virtual void CubeRotations(string direction, string times, string expected_Color, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cube Rotations", exampleTags);
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.Given("a cube with a visible \"White\" face", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
 testRunner.When(string.Format("the cube turns \"{0}\" {1} times", direction, times), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 6
 testRunner.Then(string.Format("the \"{0}\" face is visible", expected_Color), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Up Face Rotations")]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "1", "Green", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "1", "Blue", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "2", "Yellow", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "2", "Yellow", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "3", "Blue", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "3", "Green", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "4", "White", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "4", "White", new string[0])]
        public virtual void UpFaceRotations(string direction, string times, string expected_Color, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Up Face Rotations", exampleTags);
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.Given("a cube with a visible \"White\" face", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 29
 testRunner.When(string.Format("turns the up face \"{0}\" {1} times", direction, times), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then(string.Format("the \"Front\" face \"First\" row is \"{0}\"", expected_Color), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Down Face Rotations")]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "1", "Green", "White", "Blue", "Yellow", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "1", "Blue", "Yellow", "Green", "White", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "2", "Yellow", "Green", "White", "Blue", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "2", "Yellow", "Green", "White", "Blue", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "3", "Blue", "Yellow", "Green", "White", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "3", "Green", "White", "Blue", "Yellow", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "4", "White", "Blue", "Yellow", "Green", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "4", "White", "Blue", "Yellow", "Green", new string[0])]
        public virtual void DownFaceRotations(string direction, string times, string front_Color, string right_Color, string back_Color, string left_Color, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Down Face Rotations", exampleTags);
#line 43
this.ScenarioSetup(scenarioInfo);
#line 44
 testRunner.Given("a cube with a visible \"White\" face", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 45
 testRunner.When(string.Format("turns the down face \"{0}\" {1} times", direction, times), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 46
 testRunner.Then(string.Format("the \"Front\" face \"Third\" row is \"{0}\"", front_Color), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 47
  testRunner.And(string.Format("the \"Right\" face \"Third\" row is \"{0}\"", right_Color), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
  testRunner.And(string.Format("the \"Back\" face \"Third\" row is \"{0}\"", back_Color), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
  testRunner.And(string.Format("the \"Left\" face \"Third\" row is \"{0}\"", left_Color), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Left Face Rotations")]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "1", "Orange", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "1", "Red", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "2", "Yellow", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "2", "Yellow", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "3", "Red", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "3", "Orange", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "4", "White", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "4", "White", new string[0])]
        public virtual void LeftFaceRotations(string direction, string times, string expected_Color, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Left Face Rotations", exampleTags);
#line 62
this.ScenarioSetup(scenarioInfo);
#line 63
 testRunner.Given("a cube with a visible \"White\" face", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 64
 testRunner.When(string.Format("turns the left face \"{0}\" {1} times", direction, times), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
 testRunner.Then(string.Format("the \"Front\" face \"First\" column is \"{0}\"", expected_Color), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Right Face Rotations")]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "1", "Red", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "1", "Orange", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "2", "Yellow", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "2", "Yellow", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "3", "Orange", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "3", "Red", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Clockwise", "4", "White", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CounterClockwise", "4", "White", new string[0])]
        public virtual void RightFaceRotations(string direction, string times, string expected_Color, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Right Face Rotations", exampleTags);
#line 78
this.ScenarioSetup(scenarioInfo);
#line 79
 testRunner.Given("a cube with a visible \"White\" face", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 80
 testRunner.When(string.Format("turns the right face \"{0}\" {1} times", direction, times), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 81
 testRunner.Then(string.Format("the \"Front\" face \"Third\" column is \"{0}\"", expected_Color), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
